ethereum:
  websocket_url: "wss://your-node-url"
  chain_id: 1

contracts:
  - name: "Vault"
    address: "0x..."
    start_block: 12345678
    abi_path: "vault.abi.json"
    events:
      - "Deposit"
      - "Withdraw"
      - "Transfer"

database:
  supabase_url: "https://your-project.supabase.co"