ethereum:
  websocket_url: "wss://your-node-url"
  chain_id: 1

contracts:
  - name: "Vault"
    address: "0x..."
    start_block: 12345678
    abi_path: "vault.abi.json"
    events:
      - "Deposit"
      - "Withdraw"
      - "Transfer"

database:
  supabase_url: "http://127.0.0.1:54321" 
  # taken from supabase local studio
  supabase_admin_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"