name: Update gomod2nix
on:
  push:
    branches:
      - main
    paths:
      - 'go.sum'
      - 'go.mod'

permissions:
  contents: write
  pull-requests: write

jobs:
  gomod2nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v28

      - name: Update gomod2nix
        run: nix develop -c 'gomod2nix' generate --outdir '${{ github.workspace }}'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update gomod2nix
          file_pattern: gomod2nix.toml
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'
