name: Run Tests

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Using a recent stable version
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./... 